export const SET_SKIN ="SET_SKIN";
export const SET_SKIN_ERROR="SET_SKIN_ERROR";
export const UPDATE_FONT_FAMILY ="UPDATE_FONT_FAMILY";
export const UPDATE_FONT_SIZE ="UPDATE_FONT_SIZE";
export const UPDATE_COLOR ="UPDATE_COLOR";

export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER = "REGISTER";
export const CHANGE_FONT_SIZE ="CHANGE_FONT_SIZE";
export const CHANGE_FONT_FAMILY ="CHANGE_FONT_FAMILY";
export const SIGN_IN ="SIGN_IN";
export const SIGN_IN_FAILED ="SIGN_IN_FAILED";

export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const UPDATE_CONTACT_ERROR="UPDATE_CONTACT_ERROR";
export const UPDATE_SKIN ="UPDATE_SKIN";
export const UPDATE_SKIN_ERROR = "UPDATE_SKIN_ERROR";
export const ADD_CONTACT ="ADD_CONTACT";
export const ADD_CONTACT_ERROR="ADD_CONTACT_ERROR";

export const ADD_EDUCATION ="ADD_EDUCATION";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";
export const SIGN_OUT ="SIGN_OUT";
export const SIGN_OUT_FAILED="SIGN_OUT_FAILED"
